steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/appcm-infinite-frq-generator/appcm-infinite-frq-generator:$COMMIT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/appcm-infinite-frq-generator/appcm-infinite-frq-generator:$COMMIT_SHA']

  # Deploy to Cloud Run with all environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'appcm-infinite-frq-generator'
      - '--image'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/appcm-infinite-frq-generator/appcm-infinite-frq-generator:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - 'FRQ=FRQ:latest'
      - '--set-env-vars'
      - 'FIREBASE_API_KEY=${_FIREBASE_API_KEY},FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN},FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID},FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET},FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID},FIREBASE_APP_ID=${_FIREBASE_APP_ID}'

# Store images in Artifact Registry
images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/appcm-infinite-frq-generator/appcm-infinite-frq-generator:$COMMIT_SHA'

# Substitution variables - set these in your Cloud Build trigger
substitutions:
  _FIREBASE_API_KEY: 'AIzaSyBy0BvarIrW1PLb1IdH30MfvXQ2wJrE2oMAIzaSyBy0BvarIrW1PLb1IdH30MfvXQ2wJrE2oM'
  _FIREBASE_AUTH_DOMAIN: 'unique-sentinel-423412-q3.firebaseapp.com'
  _FIREBASE_PROJECT_ID: 'unique-sentinel-423412-q3'
  _FIREBASE_STORAGE_BUCKET: 'unique-sentinel-423412-q3.firebasestorage.app'
  _FIREBASE_MESSAGING_SENDER_ID: '145857450332'
  _FIREBASE_APP_ID: '1:145857450332:web:b9e589f9861a7736a03199'

options:
  logging: CLOUD_LOGGING_ONLY
