import React, { useState } from 'react';
import { UNITS, FRQ_TYPES } from '../constants';
import { Unit, FRQType } from '../types';

interface Props {
  onGenerate: (type: FRQType, selectedUnits: Unit[], selectedSubTopics: string[]) => void;
}

const SelectionScreen: React.FC<Props> = ({ onGenerate }) => {
  const [selectedType, setSelectedType] = useState<FRQType | null>(null);
  const [selectedUnits, setSelectedUnits] = useState<Unit[]>([]);
  const [selectedSubTopics, setSelectedSubTopics] = useState<string[]>([]);
  const [expandedUnits, setExpandedUnits] = useState<Unit[]>([]);

  const toggleUnitExpanded = (unit: Unit) => {
    setExpandedUnits(prev =>
      prev.includes(unit) ? prev.filter(u => u !== unit) : [...prev, unit]
    );
  };

  const toggleSubTopic = (id: string) => {
    setSelectedSubTopics(prev =>
      prev.includes(id) ? prev.filter(s => s !== id) : [...prev, id]
    );
  };

  const toggleUnitSelected = (unit: Unit) => {
    const unitData = UNITS.find(u => u.id === unit);
    if (!unitData) return;
    const unitTopicIds = unitData.subTopics.map(s => s.id);

    if (selectedUnits.includes(unit)) {
      // Deselect unit and clear its topics
      setSelectedUnits(selectedUnits.filter(u => u !== unit));
      setSelectedSubTopics(selectedSubTopics.filter(id => !unitTopicIds.includes(id)));
    } else {
      // Select unit and all its topics
      setSelectedUnits([...selectedUnits, unit]);
      const merged = Array.from(new Set([...selectedSubTopics, ...unitTopicIds]));
      setSelectedSubTopics(merged);
    }
  };

  const clearAll = () => {
    setSelectedUnits([]);
    setSelectedSubTopics([]);
  };

  const handleGenerate = () => {
    if (!selectedType) return;
    onGenerate(selectedType, selectedUnits, selectedSubTopics);
  };

  const handleRandom = () => {
    if (!selectedType) return;
    // Pass empty arrays — geminiService will pick a random topic pool.
    onGenerate(selectedType, [], []);
  };

  const totalSelected = selectedSubTopics.length;

  return (
    <div className="max-w-5xl mx-auto p-6 space-y-8 animate-fade-in">
      <div className="text-center space-y-2">
        <h1 className="text-4xl font-bold text-indigo-900">AP Chemistry</h1>
        <p className="text-xl text-indigo-600">Infinite FRQ Generator</p>
        <p className="text-sm text-gray-500">CED · Short Answer and Long Answer</p>
      </div>

      {/* FRQ Type Selection */}
      <div className="bg-white p-6 rounded-xl shadow-lg border border-indigo-50">
        <h2 className="text-lg font-semibold mb-4 flex items-center">
          <span className="bg-indigo-100 text-indigo-800 w-8 h-8 rounded-full flex items-center justify-center mr-2">1</span>
          Select FRQ Type
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {FRQ_TYPES.map((type) => (
            <button
              key={type.id}
              onClick={() => setSelectedType(type.id)}
              className={`text-left p-4 rounded-lg border transition-all ${
                selectedType === type.id
                  ? 'border-indigo-500 bg-indigo-50 ring-2 ring-indigo-200'
                  : 'border-gray-200 hover:border-indigo-300 hover:bg-gray-50'
              }`}
            >
              <div className="font-medium">{type.name}</div>
              <div className="text-sm text-gray-500 mt-1">{type.desc}</div>
            </button>
          ))}
        </div>
      </div>

      {/* Topic Selection */}
      <div className="bg-white p-6 rounded-xl shadow-lg border border-indigo-50">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-semibold flex items-center">
            <span className="bg-indigo-100 text-indigo-800 w-8 h-8 rounded-full flex items-center justify-center mr-2">2</span>
            Select Units and/or Topics
          </h2>
          <div className="text-sm text-gray-500">
            {totalSelected > 0 && (
              <>
                {`${totalSelected} topic${totalSelected === 1 ? '' : 's'} selected`}
                <button onClick={clearAll} className="ml-3 text-indigo-600 hover:underline">Clear all</button>
              </>
            )}
          </div>
        </div>

        <p className="text-xs text-gray-500 mb-4">
          You can select topics from one or more units. Leave everything unchecked for a question generated by a random selection of units/topics.
        </p>

        <div className="space-y-3">
          {UNITS.map((unit) => {
            const isUnitSelected = selectedUnits.includes(unit.id);
            const isExpanded = expandedUnits.includes(unit.id);
            const unitTopicIdsSet = new Set(unit.subTopics.map(s => s.id));
            const selectedInUnit = selectedSubTopics.filter(id => unitTopicIdsSet.has(id)).length;

            return (
              <div key={unit.id} className="border border-gray-200 rounded-lg">
                <div className="flex items-center justify-between p-3 bg-gray-50 rounded-t-lg">
                  <label className="flex items-center space-x-3 cursor-pointer flex-1">
                    <input
                      type="checkbox"
                      checked={isUnitSelected}
                      onChange={() => toggleUnitSelected(unit.id)}
                      className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
                    />
                    <span className="font-medium text-gray-900">{unit.name}</span>
                    {selectedInUnit > 0 && (
                      <span className="text-xs text-indigo-600 bg-indigo-100 px-2 py-0.5 rounded-full">
                        {selectedInUnit}/{unit.subTopics.length}
                      </span>
                    )}
                  </label>
                  <button
                    onClick={() => toggleUnitExpanded(unit.id)}
                    className="text-xs text-indigo-600 hover:underline ml-2"
                  >
                    {isExpanded ? 'Collapse' : 'Topics'}
                  </button>
                </div>
                {isExpanded && (
                  <div className="p-3 space-y-2 bg-white rounded-b-lg">
                    {unit.subTopics.map((sub) => (
                      <label key={sub.id} className="flex items-center space-x-3 p-2 hover:bg-gray-50 rounded cursor-pointer">
                        <input
                          type="checkbox"
                          checked={selectedSubTopics.includes(sub.id)}
                          onChange={() => toggleSubTopic(sub.id)}
                          className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
                        />
                        <span className="text-sm text-gray-700">{sub.id} {sub.name}</span>
                      </label>
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Generate Buttons */}
      <div className="flex justify-center items-center gap-4 pt-2 pb-8">
        <button
          onClick={handleGenerate}
          disabled={!selectedType}
          className={`px-8 py-4 rounded-full text-lg font-semibold text-white shadow-lg transition-all transform hover:scale-105 ${
            selectedType
              ? 'bg-indigo-600 hover:bg-indigo-700 hover:shadow-xl'
              : 'bg-gray-300 cursor-not-allowed'
          }`}
        >
          {totalSelected > 0 ? 'Generate Question' : 'Generate Random Question'}
        </button>
        {totalSelected > 0 && (
          <button
            onClick={handleRandom}
            disabled={!selectedType}
            className={`px-6 py-4 rounded-full text-base font-semibold border transition-all ${
              selectedType
                ? 'bg-white text-indigo-600 border-indigo-600 hover:bg-indigo-50'
                : 'bg-gray-100 text-gray-400 border-gray-200 cursor-not-allowed'
            }`}
            title="Ignore your selections and pick random topics"
          >
            Random instead
          </button>
        )}
      </div>
    </div>
  );
};

export default SelectionScreen;
